__author__ = 'Blake'

DEFAULT_INDEX_HTML = '''
<html>
    <head>
        <title>Generated by Synpost</title>
    </head>
    <body>
        <h1>Hi!</h1>
        This page was automatically generated by Synpost!
        <br>
        See, https://github.com/blakev/synpost for help on getting started :)
        <br>
        <hr>
    </body>
</html>
'''